Update NativeInput.hx
HaxeFoundation/haxe pull request #5063
Opened 2016-04-06 16:16 UTC by cambeyer

C# Stream.Read() may give "A non-blocking socket operation could not be completed immediately." when it is eof.

2016-04-06 16:33 UTC, cambeyer commented
To avoid try/catch, may also use something like:

var asyncRead:cs.system.IAsyncResult = stream.BeginRead(s.getData(),pos,len,null,null);
asyncRead.AsyncWaitHandle.WaitOne();
var ret = stream.EndRead(asyncRead);

2018-04-30 06:56 UTC, Simn commented
Can we be sure that `s.getData()` doesn't cause an exception which incorrectly is caught by that try catch?

2018-05-03 22:56 UTC, cambeyer commented
Yeah that was kind of what I was thinking too... what do you think of the alternative from my other comment?

2018-09-08 09:08 UTC, Simn requested changes

2018-09-08 09:08 UTC, Simn commented on std/cs/io/NativeInput.hx
> +			ret = stream.Read(s.getData(), pos, len);
The `s.getData()` should not be within the try-catch.

2019-09-09 15:21 UTC, closed without merging