Add a "wildcard*" exclusion option to ignore param in haxe.macro.Compiler's include method
HaxeFoundation/haxe pull request #6570
Opened 2017-09-09 11:56 UTC by mastef

Example use case : 

`<haxeflag name="--macro include('package', true, ['package.subclasses*'])" />`

This will allow for a - still basic - but more versatile exclusion matching

2017-09-11 08:44 UTC, Simn commented
I was thinking that we should just use regular expressions for all these dot-path filters. The problem is that `.` would technically have to be escaped as `\.`...

2017-09-11 09:50 UTC, mastef commented
@simn Yeah I didn't want to break existing rules, so just did something very simplistic that would give the biggest reward with the least incompatibility

2017-09-22 13:01 UTC, Simn commented
I'm okay with the feature, but not with the implementation. It has to walk all ignore filters for all files and check which of them are wildcard filters. This should only be done _once_. How about simply separating the filters into wildcard/non-wildcard ones? That way the skip function can use Lambda.has for the non-wildcard ones and check for startsWith on the wildcard ones.

2017-12-16 16:32 UTC, mastef commented
Ok, @Simn I've adjusted the implementation based on your feedback

2018-04-20 05:53 UTC, Simn requested changes

2018-04-20 05:53 UTC, Simn commented on std/haxe/macro/Compiler.hx
> +		var ignore_wildcard:Array<String> = [];
Inconsistent naming, please use `ignoreWildcard`.

2018-04-20 05:53 UTC, Simn commented on std/haxe/macro/Compiler.hx
> +					ignore_wildcard.push(ignore[i].substr(0, ignore[i].length-1));
What's the point of this `substr`?

2018-04-20 05:53 UTC, Simn commented on std/haxe/macro/Compiler.hx
> +					ignore.splice(i, 1);
It's probably better to just construct two arrays instead of modifying one of them. You shouldn't modify while iterating anyway.

2018-04-20 06:24 UTC, mastef commented
Ok, @Simn I've adjusted the implementation based on your feedback

2018-04-21 06:50 UTC, Simn approved these changes

2018-04-21 06:50 UTC, merged

2018-04-21 06:50 UTC, Simn commented
Thanks!