Add ReadOnlyArray
HaxeFoundation/haxe pull request #7467
Opened 2018-09-24 12:47 UTC by kevinresol

2018-09-24 13:28 UTC, Gama11 commented on std/haxe/ds/ReadOnlyArray.hx
> +  @:arrayAccess public inline function get(i:Int) return this[i];
I wonder if this should maybe be private, since you can't call `get()` on a regular array either (the `[]` operator would still work).

2018-09-24 14:24 UTC, RealyUniqueName requested changes
Need to add `length` field directly to the abstract fields instead of forwarding it.
Otherwise iterating over `ReadOnlyArray` will allocate an iterator: http://try-haxe.mrcdk.com/#58627
Related issue: https://github.com/HaxeFoundation/haxe/issues/5981#issuecomment-321536273

2018-09-24 15:23 UTC, RealyUniqueName commented on std/haxe/ds/ReadOnlyArray.hx
> +  var length(get,never):Int;
and it should be public )

2018-09-24 15:23 UTC, back2dos commented
@Simn any ideas how we might get array pattern matching for this (and perhaps even anything with length and array access)?

2018-09-24 15:42 UTC, RealyUniqueName approved these changes

2018-09-25 06:10 UTC, Simn commented
I can take a look at the pattern matching. We just have to make sure that the pattern matcher can figure out what the element type is.

2018-09-25 06:23 UTC, Simn commented
Should work now. Note that the `from Array<T>` is required because otherwise it won't let you assign the pattern to the subject type. I'm not sure if that restriction is strictly necessary because the pattern shouldn't be understood as an `Array` type in the first place. But let's go with this for now.

2018-09-25 06:58 UTC, frabbit commented
Hmm, should we use ReadOnly or Readonly.

2018-09-25 12:39 UTC, haxiomic commented
> Hmm, should we use ReadOnly or Readonly.

ReadOnly to be consistent with the rest of instances in std

2018-09-25 14:52 UTC, frabbit commented
@Simn couldn't we use the idea of `@:match` metadata for the pattern matching. In this case:
`@:match inline function match () return this;`

2018-09-25 15:04 UTC, Simn commented
Maybe... I think we need a haxe-evolution for these pseudo-casts. This also relates to your fromNothing and Juraj's from-expected-type idea.

2018-09-25 15:43 UTC, RealyUniqueName commented
Let's merge this PR for now

2018-09-27 05:27 UTC, Simn commented
I don't mean to be a nuisance, but can we at least get a brief documentation on the type?

2018-09-27 09:47 UTC, merged

2018-09-27 09:47 UTC, Simn commented
Thanks!