[php] Fix unsign right shift
HaxeFoundation/haxe pull request #7571
Opened 2018-10-23 18:16 UTC by flashultra

At the moment right shift is signed.

2018-10-23 18:19 UTC, Simn commented
For future reference: Please send PRs from a separate branch, not "development".

2018-10-23 20:35 UTC, RealyUniqueName requested changes
Please, add a test case.

2018-10-24 07:03 UTC, RealyUniqueName approved these changes

2018-10-24 07:09 UTC, merged

2018-10-24 07:10 UTC, RealyUniqueName commented
Details here https://github.com/HaxeFoundation/haxe/issues/7533#issuecomment-431894664