haxe.io.Bytes documentation.
HaxeFoundation/haxe pull request #8552
Opened 2019-07-15 14:56 UTC by cancerberoSgx

As a new user it took me some time to figure out what undocumented methods of haxe.io.Bytes do. Knowing exactly the behavior or this class is important for performance and with simple comments like these it should be enough. Thanks.

2019-07-15 16:17 UTC, Aurel300 requested changes

2019-07-15 16:17 UTC, Aurel300 commented on std/haxe/io/Bytes.hx
> +	  Copies `len` bytes from `src` into this instance.
What about the other arguments? `len` bytes are copied, that's true. The destination is `pos` bytes into `this` instance, and the source is `srcpos` bytes into `src`.

2019-07-15 16:17 UTC, Aurel300 commented on std/haxe/io/Bytes.hx
> +	  Sets the value of this instance's `len` bytes to `value`, starting from index `pos`.
"Sets `len` consecutive bytes starting from index `pos` of `this` instance to `value`."

2019-07-15 16:17 UTC, Aurel300 commented on std/haxe/io/Bytes.hx
> +	  Returns a new `Bytes` instance that contains a copy of this instance's `len` bytes, starting at index `pos`.
"… that contains a copy of `len` bytes of `this` instance, starting at index `pos`."

2019-07-15 16:17 UTC, Aurel300 commented on std/haxe/io/Bytes.hx
> +	  different than `0` otherwise.
Non-zero values also have a meaning, it should be lexicographic comparison (negative value if `this` is shorter or same length + lexicographically comes first, positive if `this` is longer or same length + lexicographically comes later second).

2019-07-19 07:25 UTC, Aurel300 requested changes

2019-07-19 07:25 UTC, Aurel300 commented on std/haxe/io/Bytes.hx
> +    @param pos Zero-based location in this instance from which to start copying bytes.
`from which to start copying` -> `at which to start writing`

2019-07-19 07:25 UTC, Aurel300 commented on std/haxe/io/Bytes.hx
> +    Sets `len` consecutive bytes starting from index `pos` of this instance to `value`.
Use tabs for indentation, please.

2019-07-19 07:25 UTC, Aurel300 commented on std/haxe/io/Bytes.hx
> +    Otherwise, returns a negative value if this instance's `length` is less than `other`'s `length` or if the
Drop the `Otherwise,`. Use tabs in this doc as well.

2019-08-17 08:25 UTC, Simn commented
@Aurel300 Can you finalize this PR?

2019-08-17 13:28 UTC, Aurel300 approved these changes

2019-08-17 13:59 UTC, merged